In [1]:
%matplotlib inline
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import math
import os

<h1>XGBoost Cloud Prediction Invocation Template</h1>
<h4>Invoke SageMaker Prediction Service</h4>

In [2]:
import boto3
import re
from sagemaker import get_execution_role
import sagemaker
import pandas as pd

In [55]:
# Acquire a realtime endpoint
endpoint_name = 'xgboost-biketrain-ver1'
predictor = sagemaker.predictor.RealTimePredictor(endpoint=endpoint_name)

In [56]:
from sagemaker.predictor import csv_serializer, json_deserializer

predictor.content_type = 'text/csv'
predictor.serializer = csv_serializer
predictor.deserializer = None

In [5]:
df_all = pd.read_csv('bike_test.csv')

In [30]:
df_all.shape

(6493, 14)

In [6]:
df_all.head()

datetime  season  holiday  workingday  weather   temp   atemp  \
0  2011-01-20 00:00:00       1        0           1        1  10.66  11.365   
1  2011-01-20 01:00:00       1        0           1        1  10.66  13.635   
2  2011-01-20 02:00:00       1        0           1        1  10.66  13.635   
3  2011-01-20 03:00:00       1        0           1        1  10.66  12.880   
4  2011-01-20 04:00:00       1        0           1        1  10.66  12.880   

   humidity  windspeed  year  month  day  dayofweek  hour  
0        56    26.0027  2011      1   20          3     0  
1        56     0.0000  2011      1   20          3     1  
2        56     0.0000  2011      1   20          3     2  
3        56    11.0014  2011      1   20          3     3  
4        56    11.0014  2011      1   20          3     4

In [27]:
df_all.columns[1:]

Index(['season', 'holiday', 'workingday', 'weather', 'temp', 'atemp',
       'humidity', 'windspeed', 'year', 'month', 'day', 'dayofweek', 'hour'],
      dtype='object')

In [48]:
# Need to pass an array to the prediction
# can pass a numpy array or a list of values [[19,1],[20,1]]
#arr_test = df_all.to_numpy(df_all.iloc[:,1:])
arr_test=df_all.iloc[:, 1:].to_numpy()

In [49]:
arr_test

array([[ 1.,  0.,  1., ..., 20.,  3.,  0.],
       [ 1.,  0.,  1., ..., 20.,  3.,  1.],
       [ 1.,  0.,  1., ..., 20.,  3.,  2.],
       ...,
       [ 1.,  0.,  1., ..., 31.,  0., 21.],
       [ 1.,  0.,  1., ..., 31.,  0., 22.],
       [ 1.,  0.,  1., ..., 31.,  0., 23.]])

In [51]:
type(arr_test)

numpy.ndarray

In [16]:
arr_test.shape

(6493, 13)

In [52]:
#Checking the 1st 5 rows of test data in array format
arr_test[:5]

array([[1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.13650e+01, 5.60000e+01, 2.60027e+01, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 0.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.36350e+01, 5.60000e+01, 0.00000e+00, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 1.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.36350e+01, 5.60000e+01, 0.00000e+00, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 2.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.28800e+01, 5.60000e+01, 1.10014e+01, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 3.00000e+00],
       [1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.28800e+01, 5.60000e+01, 1.10014e+01, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 4.00000e+00]])

In [29]:
arr_test[:1]

array([[1.00000e+00, 0.00000e+00, 1.00000e+00, 1.00000e+00, 1.06600e+01,
        1.13650e+01, 5.60000e+01, 2.60027e+01, 2.01100e+03, 1.00000e+00,
        2.00000e+01, 3.00000e+00, 0.00000e+00]])

In [57]:
#Predicting for the last 2 records
result = predictor.predict(arr_test[:2])

In [58]:
result

b'11.445718765258789,0.4072710871696472'

In [59]:
# For large number of predictions, we can split the input data and
# Query the prediction service.
# array_split is convenient to specify how many splits are needed
predictions = []
for arr in np.array_split(arr_test,10):
    result = predictor.predict(arr)
    result = result.decode("utf-8")
    result = result.split(',')
    print (arr.shape)
    predictions += [float(r) for r in result]

(650, 13)
(650, 13)
(650, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)
(649, 13)


In [60]:
len(predictions)

6493

In [61]:
#Loading the top-10 predictions
predictions[1:10]

[0.4072710871696472,
 -5.09121561050415,
 -3.098048210144043,
 -3.098048210144043,
 8.954294204711914,
 35.636985778808594,
 108.14555358886719,
 248.1470489501953,
 113.91631317138672]

In [63]:
np.expm1(predictions)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in expm1
  if __name__ == '__main__':


array([ 9.34991917e+04,  5.02711416e-01, -9.93849461e-01, ...,
        4.21640732e+59,  4.10840794e+36,  2.73576537e+20])

In [64]:
df_all['count'] = np.expm1(predictions)

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/ipykernel/__main__.py:1: RuntimeWarning: overflow encountered in expm1
  if __name__ == '__main__':


In [46]:
df_all.head()

datetime  season  holiday  workingday  weather   temp   atemp  \
0  2011-01-20 00:00:00       1        0           1        1  10.66  11.365   
1  2011-01-20 01:00:00       1        0           1        1  10.66  13.635   
2  2011-01-20 02:00:00       1        0           1        1  10.66  13.635   
3  2011-01-20 03:00:00       1        0           1        1  10.66  12.880   
4  2011-01-20 04:00:00       1        0           1        1  10.66  12.880   

   humidity  windspeed  year  month  day  dayofweek  hour      count  
0        56    26.0027  2011      1   20          3     0  17.756274  
1        56     0.0000  2011      1   20          3     1  -0.985659  
2        56     0.0000  2011      1   20          3     2  -0.999902  
3        56    11.0014  2011      1   20          3     3  -0.999385  
4        56    11.0014  2011      1   20          3     4  -0.999385

In [65]:
df_all[['datetime','count']].to_csv('predicted_count_cloud.csv',index=False)